services:
  postgres:
    image: postgres:15-alpine
    container_name: shopflow_pg
    restart: always
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*", "-p", "5432"]
    volumes:
      - /root/task/data/pgdata:/var/lib/postgresql/data
    networks:
      - shopflow_net
    environment:
      - POSTGRES_USER=shopuser
      - POSTGRES_PASSWORD=shoppass
      - POSTGRES_DB=shopflow
  shopflow_api:
    build:
      context: /root/task
      dockerfile: Dockerfile
    container_name: shopflow_api
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - /root/task:/root/task
    networks:
      - shopflow_net
networks:
  shopflow_net:
    driver: bridge
